name: realhome
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+17

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_storage: 
  cloud_firestore: ^0.12.9+5
  provider: ^3.0.0
  provider_architecture:
  flutter_spinkit: ^4.1.2+1
  get_it:
  image_picker: 
  firebase_admob: ^0.9.0+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.2
  firebase_messaging: ^6.0.13
  http: ^0.12.0+4
  animated_text_kit: ^2.0.0
  image_cropper: ^1.2.1
  shared_preferences: ^0.5.6+3
  uuid: ^2.0.4
  google_maps_flutter: ^0.5.26+4
  location: ^3.0.2
  carousel_slider: ^2.0.0
  fluttertoast: ^4.0.1
  flutter_picker: ^1.1.3
  geolocator: ^5.1.5
  flutter_typeahead:
  url_launcher: ^5.4.5
  localstorage: ^3.0.2+5
  flutter_native_admob: ^2.1.0
  flutter_local_notifications: 1.4.0
  photo_view: ^0.5.0
  intl: ^0.15.7
  cached_network_image: 2.0.0-rc
  google_fonts: ^1.1.0
  custom_switch: ^0.0.1
  multi_image_picker: ^4.6.7
  flutter_absolute_path: ^1.0.6
  path_provider: ^1.6.8
  firebase_analytics: ^5.0.11
  firebase_remote_config: ^0.3.0+3
  image: ^2.1.12






  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/text/
    # - assets/images/google_logo.png
    # - assets/images/logo.png
    # - assets/images/title.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
